# Site Settings
title: Nipender Singh
url: 'http://webjeda.com'
baseurl: '/resume' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Nipender Sigh
tagline: Digital Marketing Expert.
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Working gives me a lot of skills and experience that 
I believe make me best suited for the job position that is
being offered with a position of Graphic Designer. I have
been working in a design industry for 5 years, with my most recent experience being a
UX  Designer at Great Designs. I possess valuable skills such as good communication and 
high creativity that I believe make me best suited for the position of UX Designer in your company'

#sidebar links
email: singhnipender@gmail.com
phone: +91 9782715171
#website: blog.webjeda.com #do not add http://
linkedin: nipender-singh
#github: sharu725
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Tracker analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
